// Source: docs/design/asset-placement.csv. Preserve original orientation.
export const ASSET_RULES = {
  "Acid puddle.png": {
    key: "reviewed-0",
    file: "Acid puddle.png",
    category: "Floor decal",
    placement: "Place on adjacent tile near acid tiles",
    blocks: "No (hazard behavior unconfirmed)",
    goesWith: "Potion Mana.png; Rock01.png",
    notes:
      "Confirm whether it is harmful, impassable, or cosmetic. Do not put an unapproved hazard on a mandatory route.",
    width: 16,
    height: 16,
  },
  "Apple.png": {
    key: "reviewed-1",
    file: "Apple.png",
    category: "Tabletop detail / pickup",
    placement: "Place on table or board",
    blocks: "No",
    goesWith: "Table Long.png; Chair01.png; Crate 01.png",
    notes:
      "Suggested decorative food. Healing or pickup behavior is unconfirmed.",
    width: 16,
    height: 16,
  },
  "Blood.png": {
    key: "reviewed-2",
    file: "Blood.png",
    category: "Floor decal",
    placement: "Place a small stain near a trap or enemy",
    blocks: "No",
    goesWith: "Skulls.png; Sword.png",
    notes: "Cosmetic by default; do not imply damage or tracking mechanics.",
    width: 16,
    height: 16,
  },
  "Board Large.png": {
    key: "reviewed-3",
    file: "Board Large.png",
    category: "Display platform",
    placement:
      "Use as a low display base against a wall or under a focal object.",
    blocks: "Yes",
    goesWith: "Throne.png; Shield.png; Vase Grey.png",
    notes:
      "Can be used similar to tables to place items but more for potions, books, or scrolls",
    width: 48,
    height: 16,
  },
  "Board Medium.png": {
    key: "reviewed-4",
    file: "Board Medium.png",
    category: "Display platform",
    placement:
      "Use as a low display base against a wall or under a focal object.",
    blocks: "Yes",
    goesWith: "Throne.png; Shield.png; Vase Grey.png",
    notes:
      "Can be used similar to tables to place items but more for potions, books, or scrolls",
    width: 32,
    height: 16,
  },
  "Board Small.png": {
    key: "reviewed-5",
    file: "Board Small.png",
    category: "Display platform",
    placement:
      "Use as a low display base against a wall or under a focal object.",
    blocks: "Yes",
    goesWith: "Throne.png; Shield.png; Vase Grey.png",
    notes:
      "Can be used similar to tables to place items but more for potions, books, or scrolls",
    width: 16,
    height: 16,
  },
  "Book Green.png": {
    key: "reviewed-6",
    file: "Book Green.png",
    category: "Tabletop / floor detail",
    placement: "Place on reading tables or sparsely beside shelves.",
    blocks: "No",
    goesWith: "Table.png; Book shelf 01.png; Pile of Books 02.png",
    notes:
      "Use colors as visual variation, not automatic rarity or magic effects.",
    width: 16,
    height: 16,
  },
  "Book Red.png": {
    key: "reviewed-7",
    file: "Book Red.png",
    category: "Tabletop / floor detail",
    placement: "Place on reading tables or sparsely beside shelves.",
    blocks: "No",
    goesWith: "Table.png; Book shelf 01.png; Pile of Books 02.png",
    notes:
      "Use colors as visual variation, not automatic rarity or magic effects.",
    width: 16,
    height: 16,
  },
  "Book Yellow.png": {
    key: "reviewed-8",
    file: "Book Yellow.png",
    category: "Tabletop / floor detail",
    placement: "Place on reading tables or sparsely beside shelves.",
    blocks: "No",
    goesWith: "Table.png; Book shelf 01.png; Pile of Books 02.png",
    notes:
      "Use colors as visual variation, not automatic rarity or magic effects.",
    width: 16,
    height: 16,
  },
  "Book shelf 01.png": {
    key: "reviewed-9",
    file: "Book shelf 01.png",
    category: "Furniture",
    placement: "Back against a solid wall. Keep the front accessible.",
    blocks: "Yes",
    goesWith: "Table.png; Chair01.png; Pile of Books 01.png",
    notes: "Group into short shelf runs with gaps at doors.",
    width: 16,
    height: 16,
  },
  "Book shelf 02.png": {
    key: "reviewed-10",
    file: "Book shelf 02.png",
    category: "Furniture",
    placement: "Back against a solid wall. Keep the front accessible.",
    blocks: "Yes",
    goesWith: "Table.png; Chair01.png; Pile of Books 01.png",
    notes:
      "Tall shelf: reserve visual clearance above its base. Do not treat sprite height as footprint depth.",
    width: 16,
    height: 28,
  },
  "Botton 01.png": {
    key: "reviewed-11",
    file: "Botton 01.png",
    category: "Interactive fixture",
    placement: "Used alongside locked doors, hidden areas, placed on the floor",
    blocks: "No",
    goesWith: "Door Closed.png; Iron Door.png",
    notes: "Used for later switch mechanics if they get added",
    width: 16,
    height: 16,
  },
  "Botton 02.png": {
    key: "reviewed-12",
    file: "Botton 02.png",
    category: "Interactive fixture",
    placement: "Used alongside locked doors, hidden areas, placed on the floor",
    blocks: "No",
    goesWith: "Door Closed.png; Iron Door.png",
    notes: "Used for later switch mechanics if they get added",
    width: 16,
    height: 16,
  },
  "Botton 03.png": {
    key: "reviewed-13",
    file: "Botton 03.png",
    category: "Interactive fixture",
    placement: "Used alongside locked doors, hidden areas, placed on the floor",
    blocks: "No",
    goesWith: "Door Closed.png; Iron Door.png",
    notes: "Used for later switch mechanics if they get added",
    width: 16,
    height: 16,
  },
  "Botton 04.png": {
    key: "reviewed-14",
    file: "Botton 04.png",
    category: "Interactive fixture",
    placement: "Used alongside locked doors, hidden areas, placed on the floor",
    blocks: "No",
    goesWith: "Door Closed.png; Iron Door.png",
    notes: "Used for later switch mechanics if they get added",
    width: 16,
    height: 16,
  },
  "Chair01.png": {
    key: "reviewed-15",
    file: "Chair01.png",
    category: "Furniture",
    placement: "Place beside a table, facing it, with space to approach.",
    blocks: "Yes",
    goesWith: "Table.png; Table Long.png",
    notes: "Front-view chair. Confirm suitable table side; do not rotate.",
    width: 16,
    height: 16,
  },
  "Chair02.png": {
    key: "reviewed-16",
    file: "Chair02.png",
    category: "Furniture",
    placement: "Place beside a table, facing it, with space to approach.",
    blocks: "Yes",
    goesWith: "Table.png; Table Long.png",
    notes:
      "Side-view chair. Use its facing direction when choosing table side.",
    width: 16,
    height: 16,
  },
  "Chest.png": {
    key: "reviewed-17",
    file: "Chest.png",
    category: "Reward container",
    placement:
      "Place in a reachable treasure alcove or against a wall, away from doorways.",
    blocks: "Yes",
    goesWith: "Gold01.png; Gold02.png; Crate 01.png",
    notes: "Should be useed with chest opening animation",
    width: 16,
    height: 16,
  },
  "Coffin.png": {
    key: "reviewed-18",
    file: "Coffin.png",
    category: "Furniture",
    placement:
      "Place lengthwise along a burial-room wall with a clear aisle beside it.",
    blocks: "Yes",
    goesWith: "Tombstone 01.png; Wall Chain 01.png; Vase Grey.png",
    notes:
      "Keep upright in the supplied orientation. Confirm footprint separately from sprite height.",
    width: 16,
    height: 32,
  },
  "Crate 01.png": {
    key: "reviewed-19",
    file: "Crate 01.png",
    category: "Furniture",
    placement:
      "Cluster against storage-room walls or in corners. Keep doors and aisles clear.",
    blocks: "Yes",
    goesWith: "Crate 01.png; Crate 02.png; Gold03.png",
    notes:
      "Mix both crate variants within small clusters rather than scattering evenly.",
    width: 16,
    height: 16,
  },
  "Crate 02.png": {
    key: "reviewed-20",
    file: "Crate 02.png",
    category: "Furniture",
    placement:
      "Cluster against storage-room walls or in corners. Keep doors and aisles clear.",
    blocks: "Yes",
    goesWith: "Crate 01.png; Crate 02.png; Gold03.png",
    notes:
      "Mix both crate variants within small clusters rather than scattering evenly.",
    width: 16,
    height: 16,
  },
  "Door Closed.png": {
    key: "reviewed-21",
    file: "Door Closed.png",
    category: "Door / connector",
    placement: "Fit a doorway and align with the matching open-door sprite.",
    blocks: "Yes while closed",
    goesWith: "Doors Open.png; Key.png; Botton 01.png",
    notes:
      "Closed double door. Opening and lock behavior require a design decision.",
    width: 32,
    height: 18,
  },
  "Door Rock.png": {
    key: "reviewed-22",
    file: "Door Rock.png",
    category: "Door / connector",
    placement: "Fit a stone doorway in a crypt or masonry wall.",
    blocks: "Yes while closed (confirm)",
    goesWith: "Coffin.png; Tombstone 02.png; Key.png",
    notes:
      "Confirm whether this is an operable door or a sealed tomb entrance.",
    width: 16,
    height: 16,
  },
  "Doors Open.png": {
    key: "reviewed-23",
    file: "Doors Open.png",
    category: "Door / connector",
    placement: "Use the same doorway footprint as the closed double door.",
    blocks: "No in opening; posts remain solid",
    goesWith: "Door Closed.png",
    notes:
      "Looks like the open counterpart of Door Closed.png. Keep the center traversable.",
    width: 32,
    height: 22,
  },
  "Flag Blue Big.png": {
    key: "reviewed-24",
    file: "Flag Blue Big.png",
    category: "Wall decoration",
    placement:
      "Hang on exposed wall faces. Space evenly or pair around a focal point.",
    blocks: "No",
    goesWith: "Lamp.png; Paiting Big.png; Throne.png",
    notes:
      "Long banner: allow vertical clearance and keep door openings clear. Preserve orientation.",
    width: 16,
    height: 32,
  },
  "Flag Blue.png": {
    key: "reviewed-25",
    file: "Flag Blue.png",
    category: "Wall decoration",
    placement:
      "Hang on exposed wall faces. Space evenly or pair around a focal point.",
    blocks: "No",
    goesWith: "Lamp.png; Paiting Big.png; Throne.png",
    notes: "Use one flag color per room or faction. Preserve orientation.",
    width: 16,
    height: 16,
  },
  "Flag Green Big.png": {
    key: "reviewed-26",
    file: "Flag Green Big.png",
    category: "Wall decoration",
    placement:
      "Hang on exposed wall faces. Space evenly or pair around a focal point.",
    blocks: "No",
    goesWith: "Lamp.png; Paiting Big.png; Throne.png",
    notes:
      "Long banner: allow vertical clearance and keep door openings clear. Preserve orientation.",
    width: 16,
    height: 32,
  },
  "Flag Green.png": {
    key: "reviewed-27",
    file: "Flag Green.png",
    category: "Wall decoration",
    placement:
      "Hang on exposed wall faces. Space evenly or pair around a focal point.",
    blocks: "No",
    goesWith: "Lamp.png; Paiting Big.png; Throne.png",
    notes: "Use one flag color per room or faction. Preserve orientation.",
    width: 16,
    height: 16,
  },
  "Flag Red Big.png": {
    key: "reviewed-28",
    file: "Flag Red Big.png",
    category: "Wall decoration",
    placement:
      "Hang on exposed wall faces. Space evenly or pair around a focal point.",
    blocks: "No",
    goesWith: "Lamp.png; Paiting Big.png; Throne.png",
    notes:
      "Long banner: allow vertical clearance and keep door openings clear. Preserve orientation.",
    width: 16,
    height: 32,
  },
  "Flag Red.png": {
    key: "reviewed-29",
    file: "Flag Red.png",
    category: "Wall decoration",
    placement:
      "Hang on exposed wall faces. Space evenly or pair around a focal point.",
    blocks: "No",
    goesWith: "Lamp.png; Paiting Big.png; Throne.png",
    notes: "Use one flag color per room or faction. Preserve orientation.",
    width: 16,
    height: 16,
  },
  "Flag Yellow Big.png": {
    key: "reviewed-30",
    file: "Flag Yellow Big.png",
    category: "Wall decoration",
    placement:
      "Hang on exposed wall faces. Space evenly or pair around a focal point.",
    blocks: "No",
    goesWith: "Lamp.png; Paiting Big.png; Throne.png",
    notes:
      "Long banner: allow vertical clearance and keep door openings clear. Preserve orientation.",
    width: 16,
    height: 32,
  },
  "Flag Yellow.png": {
    key: "reviewed-31",
    file: "Flag Yellow.png",
    category: "Wall decoration",
    placement:
      "Hang on exposed wall faces. Space evenly or pair around a focal point.",
    blocks: "No",
    goesWith: "Lamp.png; Paiting Big.png; Throne.png",
    notes: "Use one flag color per room or faction. Preserve orientation.",
    width: 16,
    height: 16,
  },
  "Gold Rock.png": {
    key: "reviewed-32",
    file: "Gold Rock.png",
    category: "Natural obstacle",
    placement:
      "Place in a mining alcove or rare treasure area beside ordinary rocks.",
    blocks: "Yes",
    goesWith: "Rock01.png; Rock02.png; Gold03.png",
    notes:
      "Looks like gold-bearing rock. Mining or resource interaction is unconfirmed.",
    width: 16,
    height: 16,
  },
  "Gold01.png": {
    key: "reviewed-33",
    file: "Gold01.png",
    category: "Pickup",
    placement: "Group on a treasure-room floor or beside a chest.",
    blocks: "No",
    goesWith: "Chest.png; Gold Rock.png",
    notes:
      "Confirm collectible gold versus purely visual treasure. Avoid implying rewards for decorative copies.",
    width: 16,
    height: 19,
  },
  "Gold02.png": {
    key: "reviewed-34",
    file: "Gold02.png",
    category: "Pickup",
    placement: "Group on a treasure-room floor or beside a chest.",
    blocks: "No",
    goesWith: "Chest.png; Gold Rock.png",
    notes:
      "Confirm collectible gold versus purely visual treasure. Avoid implying rewards for decorative copies.",
    width: 16,
    height: 16,
  },
  "Gold03.png": {
    key: "reviewed-35",
    file: "Gold03.png",
    category: "Pickup",
    placement: "Group on a treasure-room floor or beside a chest.",
    blocks: "No",
    goesWith: "Chest.png; Gold Rock.png",
    notes:
      "Confirm collectible gold versus purely visual treasure. Avoid implying rewards for decorative copies.",
    width: 16,
    height: 16,
  },
  "Iron Door.png": {
    key: "reviewed-36",
    file: "Iron Door.png",
    category: "Door / connector",
    placement: "Use at a cell or barred enclosure entrance.",
    blocks: "Yes while closed",
    goesWith: "Iron Fance.png; Wall Chain 01.png",
    notes: "Confirm operable gate versus fixed barred opening.",
    width: 16,
    height: 16,
  },
  "Iron Fance Moss.png": {
    key: "reviewed-37",
    file: "Iron Fance Moss.png",
    category: "Barrier",
    placement:
      "Join into straight railing runs at enclosure edges. Leave a deliberate opening.",
    blocks: "Yes",
    goesWith: "Iron Door.png; Wall Chain 02.png",
    notes:
      "Weathered variant for damp or abandoned rooms. Preserve upright orientation.",
    width: 16,
    height: 16,
  },
  "Iron Fance.png": {
    key: "reviewed-38",
    file: "Iron Fance.png",
    category: "Barrier",
    placement:
      "Join into straight railing runs at enclosure edges. Leave a deliberate opening.",
    blocks: "Yes",
    goesWith: "Iron Door.png; Wall Chain 02.png",
    notes: "Preserve upright orientation; verify end connections.",
    width: 16,
    height: 16,
  },
  "Key.png": {
    key: "reviewed-39",
    file: "Key.png",
    category: "Pickup",
    placement:
      "Place on reachable floor or a display table must be associated with a locked door or chest.",
    blocks: "No",
    goesWith: "Door Closed.png; Iron Door.png",
    notes:
      "Only use as a reward if a corresponding key/lock mechanic is approved.",
    width: 16,
    height: 16,
  },
  "Lamp Big.png": {
    key: "reviewed-40",
    file: "Lamp Big.png",
    category: "Lighting / fixture",
    placement:
      "Place upright beside entrances or along room edges, spaced between other fixtures.",
    blocks: "Yes (base only)",
    goesWith: "Flag Green.png; Iron Door.png; Throne.png",
    notes:
      "Looks like a standing lamp/post rather than a flame sprite. Confirm floor-mounted versus wall-mounted use and light effect.",
    width: 16,
    height: 32,
  },
  "Lamp.png": {
    key: "reviewed-41",
    file: "Lamp.png",
    category: "Lighting / fixture",
    placement:
      "Place upright beside entrances or along room edges, spaced between other fixtures.",
    blocks: "Yes",
    goesWith: "Flag Green.png; Iron Door.png; Throne.png",
    notes:
      "Looks like a standing lamp/post rather than a flame sprite. Confirm floor-mounted versus wall-mounted use and light effect.",
    width: 16,
    height: 16,
  },
  "Paiting 1.png": {
    key: "reviewed-42",
    file: "Paiting 1.png",
    category: "Wall decoration",
    placement: "Mount on a clear back wall keep multiple painting density low",
    blocks: "No",
    goesWith: "Table.png; Book shelf 01.png; Lamp.png",
    notes: "Keep upright. Do not put on floors or across door openings.",
    width: 16,
    height: 16,
  },
  "Paiting 2.png": {
    key: "reviewed-43",
    file: "Paiting 2.png",
    category: "Wall decoration",
    placement: "Mount on a clear back wall keep multiple painting density low",
    blocks: "No",
    goesWith: "Table.png; Book shelf 01.png; Lamp.png",
    notes: "Keep upright. Do not put on floors or across door openings.",
    width: 16,
    height: 16,
  },
  "Paiting 3.png": {
    key: "reviewed-44",
    file: "Paiting 3.png",
    category: "Wall decoration",
    placement: "Mount on a clear back wall keep multiple painting density low",
    blocks: "No",
    goesWith: "Table.png; Book shelf 01.png; Lamp.png",
    notes: "Keep upright. Do not put on floors or across door openings.",
    width: 16,
    height: 16,
  },
  "Paiting 4.png": {
    key: "reviewed-45",
    file: "Paiting 4.png",
    category: "Wall decoration",
    placement: "Mount on a clear back wall keep multiple painting density low",
    blocks: "No",
    goesWith: "Table.png; Book shelf 01.png; Lamp.png",
    notes: "Keep upright. Do not put on floors or across door openings.",
    width: 16,
    height: 16,
  },
  "Paiting Big.png": {
    key: "reviewed-46",
    file: "Paiting Big.png",
    category: "Wall decoration",
    placement: "Mount on a clear back wall keep multiple painting density low",
    blocks: "No",
    goesWith: "Table.png; Book shelf 01.png; Lamp.png",
    notes: "Use as an occasional focal point above a throne or reading area.",
    width: 20,
    height: 22,
  },
  "Pile of Books 01.png": {
    key: "reviewed-47",
    file: "Pile of Books 01.png",
    category: "Floor / tabletop detail",
    placement: "Place on ground near book shelf or on tables or boards",
    blocks: "No",
    goesWith: "Book shelf 01.png; Book shelf 02.png; Table.png",
    notes:
      "Small stack is proposed cosmetic; confirm whether tall stacks should block.",
    width: 16,
    height: 16,
  },
  "Pile of Books 02.png": {
    key: "reviewed-48",
    file: "Pile of Books 02.png",
    category: "Floor / tabletop detail",
    placement: "Place on ground near book shelf or on tables or boards",
    blocks: "No",
    goesWith: "Book shelf 01.png; Book shelf 02.png; Table.png",
    notes:
      "Small stack is proposed cosmetic; confirm whether tall stacks should block.",
    width: 16,
    height: 16,
  },
  "Potion HP.png": {
    key: "reviewed-49",
    file: "Potion HP.png",
    category: "Pickup / tabletop detail",
    placement: "Place on a supply table or reachable reward tile sparingly",
    blocks: "No",
    goesWith: "Table.png; Scroll.png; Chest.png",
    notes: "Health potion appearance. Confirm pickup versus cosmetic bottle.",
    width: 16,
    height: 16,
  },
  "Potion Mana.png": {
    key: "reviewed-50",
    file: "Potion Mana.png",
    category: "Pickup / tabletop detail",
    placement: "Place on a supply table or reachable reward tile sparingly",
    blocks: "No",
    goesWith: "Table.png; Scroll.png; Chest.png",
    notes: "Mana potion appearance. Confirm pickup versus cosmetic bottle.",
    width: 16,
    height: 16,
  },
  "Rock01.png": {
    key: "reviewed-51",
    file: "Rock01.png",
    category: "Natural obstacle",
    placement:
      "Cluster near cave edges or ruined wall sections, leaving routes around them.",
    blocks: "Yes",
    goesWith: "Rock01.png; Rock02.png; Skulls.png",
    notes:
      "Small rock: proposed solid obstacle; confirm whether you prefer cosmetic rubble.",
    width: 16,
    height: 16,
  },
  "Rock02.png": {
    key: "reviewed-52",
    file: "Rock02.png",
    category: "Natural obstacle",
    placement:
      "Cluster near cave edges or ruined wall sections, leaving routes around them.",
    blocks: "Yes",
    goesWith: "Rock01.png; Rock02.png; Skulls.png",
    notes: "Larger rock: check collision footprint.",
    width: 16,
    height: 16,
  },
  "Scroll.png": {
    key: "reviewed-53",
    file: "Scroll.png",
    category: "Tabletop detail / pickup",
    placement: "Place on a desk, shelf display, or reachable reward tile.",
    blocks: "No",
    goesWith: "Table.png; Book Red.png; Potion Mana.png",
    notes: "Confirm decorative scroll versus readable or collectible item.",
    width: 16,
    height: 16,
  },
  "Shield.png": {
    key: "reviewed-54",
    file: "Shield.png",
    category: "Equipment display / pickup",
    placement:
      "Display on an armory wall or table; use floor placement only for deliberate loot.",
    blocks: "No",
    goesWith: "Sword.png; Shield.png; Crate 01.png",
    notes:
      "Confirm wall-mounted display versus dropped equipment. Preserve lighting when mirroring.",
    width: 16,
    height: 16,
  },
  "Skulls.png": {
    key: "reviewed-55",
    file: "Skulls.png",
    category: "Floor detail",
    placement:
      "Scatter sparingly near coffins, ruined walls, or burial corners.",
    blocks: "No",
    goesWith: "Coffin.png; Tombstone 01.png; Rock01.png",
    notes: "Keep density low so skulls read as a deliberate location detail.",
    width: 16,
    height: 16,
  },
  "Sword.png": {
    key: "reviewed-56",
    file: "Sword.png",
    category: "Equipment display / pickup",
    placement:
      "Display on an armory wall or table; use floor placement only for deliberate loot.",
    blocks: "No",
    goesWith: "Sword.png; Shield.png; Crate 01.png",
    notes:
      "Confirm wall-mounted display versus dropped equipment. Preserve lighting when mirroring.",
    width: 16,
    height: 16,
  },
  "Table Long.png": {
    key: "reviewed-57",
    file: "Table Long.png",
    category: "Furniture",
    placement:
      "Place in reading, throne rooms, dining areas with a clear aisle around the group.",
    blocks: "Yes",
    goesWith: "Chair01.png; Chair02.png; Book Red.png; Apple.png",
    notes:
      "Long table: use multiple chairs along its length. Confirm base footprint from the sprite.",
    width: 32,
    height: 16,
  },
  "Table.png": {
    key: "reviewed-58",
    file: "Table.png",
    category: "Furniture",
    placement:
      "Place in reading, throne rooms, dining areas with a clear aisle around the group.",
    blocks: "Yes",
    goesWith: "Chair01.png; Chair02.png; Book Red.png; Apple.png",
    notes:
      "Keep horizontal. Small items may sit on top without extra ground collision.",
    width: 16,
    height: 16,
  },
  "Throne.png": {
    key: "reviewed-59",
    file: "Throne.png",
    category: "Furniture",
    placement:
      "Center against the back wall of a ceremonial room. or on higher ground must have room to approach",
    blocks: "Yes",
    goesWith: "Flag Red Big.png; Paiting Big.png; Lamp Big.png",
    notes: "Rare focal point. Face into the room.",
    width: 16,
    height: 25,
  },
  "Tombstone 01.png": {
    key: "reviewed-60",
    file: "Tombstone 01.png",
    category: "Furniture",
    placement:
      "Use burial alcoves or orderly memorial rows with clear approaches.",
    blocks: "Yes",
    goesWith: "Coffin.png; Vase Grey.png; Skulls.png",
    notes:
      "Keep upright. Pair with a memorial or coffin rather than unrelated storage.",
    width: 16,
    height: 16,
  },
  "Tombstone 02.png": {
    key: "reviewed-61",
    file: "Tombstone 02.png",
    category: "Furniture",
    placement:
      "Use burial alcoves or orderly memorial rows with clear approaches.",
    blocks: "Yes",
    goesWith: "Coffin.png; Vase Grey.png; Skulls.png",
    notes:
      "Keep upright. Pair with a memorial or coffin rather than unrelated storage.",
    width: 16,
    height: 16,
  },
  "Tombstone Moss.png": {
    key: "reviewed-62",
    file: "Tombstone Moss.png",
    category: "Furniture",
    placement:
      "Use burial alcoves or orderly memorial rows with clear approaches.",
    blocks: "Yes",
    goesWith: "Coffin.png; Vase Grey.png; Skulls.png",
    notes: "Prefer damp or abandoned burial areas.",
    width: 16,
    height: 16,
  },
  "Vase Grey Broken.png": {
    key: "reviewed-63",
    file: "Vase Grey Broken.png",
    category: "Floor detail",
    placement:
      "Place sparse fragments near intact vases or abandoned room edges.",
    blocks: "No",
    goesWith: "Vase Grey.png; Vase Yellow.png; Rock01.png",
    notes:
      "Suggested cosmetic debris. Do not imply a breakable-object mechanic unless approved.",
    width: 16,
    height: 16,
  },
  "Vase Grey.png": {
    key: "reviewed-64",
    file: "Vase Grey.png",
    category: "Furniture",
    placement:
      "Place in corners, along walls, or in pairs flanking a memorial.",
    blocks: "Yes",
    goesWith: "Coffin.png; Tombstone 02.png; Throne.png",
    notes: "Use small groups. Keep central travel lanes open.",
    width: 16,
    height: 16,
  },
  "Vase Yellow Broken.png": {
    key: "reviewed-65",
    file: "Vase Yellow Broken.png",
    category: "Floor detail",
    placement:
      "Place sparse fragments near intact vases or abandoned room edges.",
    blocks: "No",
    goesWith: "Vase Grey.png; Vase Yellow.png; Rock01.png",
    notes:
      "Suggested cosmetic debris. Do not imply a breakable-object mechanic unless approved.",
    width: 16,
    height: 16,
  },
  "Vase Yellow.png": {
    key: "reviewed-66",
    file: "Vase Yellow.png",
    category: "Furniture",
    placement:
      "Place in corners, along walls, or in pairs flanking a memorial.",
    blocks: "Yes",
    goesWith: "Coffin.png; Tombstone 02.png; Throne.png",
    notes: "Use small groups. Keep central travel lanes open.",
    width: 16,
    height: 16,
  },
  "Wall Chain 01.png": {
    key: "reviewed-67",
    file: "Wall Chain 01.png",
    category: "Wall decoration",
    placement:
      "Attach to exposed wall faces in cells, burial rooms, dining areas",
    blocks: "No",
    goesWith: "Iron Door.png; Coffin.png; Lamp.png",
    notes: "Use sparse pairs. Not a freestanding floor obstacle.",
    width: 16,
    height: 16,
  },
  "Wall Chain 02.png": {
    key: "reviewed-68",
    file: "Wall Chain 02.png",
    category: "Wall decoration",
    placement:
      "Attach to exposed wall faces in cells, burial rooms, dining areas",
    blocks: "No",
    goesWith: "Iron Door.png; Coffin.png; Lamp.png",
    notes: "Use sparse pairs. Not a freestanding floor obstacle.",
    width: 16,
    height: 16,
  },
};
export function asset(file) {
  const a = ASSET_RULES[file];
  if (!a) throw Error("Unknown reviewed asset: " + file);
  return {
    file,
    key: a.key,
    w: Math.ceil(a.width / 16),
    h: file === "Coffin.png" ? 2 : 1,
    solid: a.blocks.startsWith("Yes"),
    rotation: 0,
  };
}
