import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const browser = await chromium.launch({headless:true});
const page = await browser.newPage({viewport:{width:1100,height:900}});
const errors=[];
page.on('pageerror', e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173/?ui=1');
await page.waitForFunction(()=>window.render_game_to_text && JSON.parse(window.render_game_to_text()).ready);
const state=()=>page.evaluate(()=>JSON.parse(window.render_game_to_text()));
async function click(x,y) { const b=await page.locator('canvas').boundingBox(); await page.mouse.click(b.x+x*b.width/360,b.y+y*b.height/640); await page.waitForTimeout(60); }
async function snap(name){await page.locator('canvas').screenshot({path:`artifacts/ui-review/${name}.png`});}
await page.evaluate(() => window.advanceTime(0));
const initial = await state();
const toBoundary = 100 - initial.patternElapsed % 100;
await page.evaluate(ms => window.advanceTime(ms), toBoundary - 1);
assert.equal((await state()).patternOffset, initial.patternOffset);
await page.evaluate(() => window.advanceTime(1));
assert.equal((await state()).patternOffset, (initial.patternOffset + 1) % initial.patternPeriod);
const oneStep = (await state()).patternOffset;
await page.evaluate(ms => window.advanceTime(ms), initial.patternPeriod * 100);
assert.equal((await state()).patternOffset, oneStep);
await snap('battle-opening');
await page.keyboard.press('p'); await page.waitForTimeout(70); assert.equal((await state()).pattern,1);
await page.keyboard.press('p'); await page.waitForTimeout(70); assert.equal((await state()).pattern,2);
await page.keyboard.press('p'); await page.waitForTimeout(70); assert.equal((await state()).pattern,0);
await click(180,536);
assert.equal((await state()).battleView, 'selection');
assert.equal((await state()).timeline.find(u => u.key === 'hero').position, 70);
await snap('battle-selection');
await click(307,355); assert.equal((await state()).target,1);
await click(310,494); assert.equal((await state()).ability,1);
await click(180,556); assert.equal((await state()).confirmed,true);
await click(180,556); assert.equal((await state()).confirmed,true);
await page.keyboard.press('2'); assert.equal((await state()).page,1);
await snap('inventory');
await click(70,350); assert.equal((await state()).selected,6);
await click(180,546); assert.equal((await state()).unlocked,7); assert.equal((await state()).gold,160);
await click(180,73); assert.equal((await state()).unlocked,7);
await click(290,73); await snap('rewards');
await click(180,522); assert.equal((await state()).gold,280);
await click(180,522); assert.equal((await state()).gold,280);
await page.keyboard.press('1'); assert.equal((await state()).page,0);
await page.setViewportSize({width:390,height:844}); await page.waitForTimeout(150);
await page.keyboard.press('2'); assert.equal((await state()).page,1); await snap('mobile');
assert.deepEqual(errors,[]);
console.log('UI review: target, ability, confirm, tabs, unlock, reward idempotence, keyboard and mobile checks passed.');
await browser.close();
